//go:build ignore
// +build ignore

package sim

//go:generate go tool cgo -godefs defs.go

/*
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include "SimConnect.h"
*/
import "C"

type SIMCONNECT_RECV C.struct_SIMCONNECT_RECV
type SIMCONNECT_RECV_FACILITY_DATA C.struct_SIMCONNECT_RECV_FACILITY_DATA
type SIMCONNECT_RECV_FACILITY_DATA_END C.struct_SIMCONNECT_RECV_FACILITY_DATA_END
type SIMCONNECT_RECV_WEATHER_OBSERVATION C.struct_SIMCONNECT_RECV_WEATHER_OBSERVATION
type SIMCONNECT_RECV_CLOUD_STATE C.struct_SIMCONNECT_RECV_CLOUD_STATE
type SIMCONNECT_RECV_EXCEPTION C.struct_SIMCONNECT_RECV_EXCEPTION
type SIMCONNECT_DATA_INITPOSITION C.struct_SIMCONNECT_DATA_INITPOSITION
type SIMCONNECT_RECV_ASSIGNED_OBJECT_ID C.struct_SIMCONNECT_RECV_ASSIGNED_OBJECT_ID
type SIMCONNECT_RECV_SIMOBJECT_DATA C.struct_SIMCONNECT_RECV_SIMOBJECT_DATA

const (
	SIMCONNECT_RECV_ID_EXCEPTION             = C.SIMCONNECT_RECV_ID_EXCEPTION
	SIMCONNECT_RECV_ID_CLOUD_STATE           = C.SIMCONNECT_RECV_ID_CLOUD_STATE
	SIMCONNECT_RECV_ID_FACILITY_DATA         = C.SIMCONNECT_RECV_ID_FACILITY_DATA
	SIMCONNECT_RECV_ID_FACILITY_DATA_END     = C.SIMCONNECT_RECV_ID_FACILITY_DATA_END
	SIMCONNECT_RECV_ID_WEATHER_OBSERVATION   = C.SIMCONNECT_RECV_ID_WEATHER_OBSERVATION
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE = C.SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE
	SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID    = C.SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA        = C.SIMCONNECT_RECV_ID_SIMOBJECT_DATA

	SIMCONNECT_FACILITY_DATA_FREQUENCY = C.SIMCONNECT_FACILITY_DATA_FREQUENCY

	SIMCONNECT_DATATYPE_INT32   = C.SIMCONNECT_DATATYPE_INT32
	SIMCONNECT_DATATYPE_FLOAT64 = C.SIMCONNECT_DATATYPE_FLOAT64
	SIMCONNECT_SIMOBJECT_TYPE_USER = C.SIMCONNECT_SIMOBJECT_TYPE_USER

	// SimConnect Period (for RequestDataOnSimObject)
	SIMCONNECT_PERIOD_ONCE = C.SIMCONNECT_PERIOD_ONCE

	// SimConnect Exception types
	SIMCONNECT_EXCEPTION_NONE                            = C.SIMCONNECT_EXCEPTION_NONE
	SIMCONNECT_EXCEPTION_ERROR                           = C.SIMCONNECT_EXCEPTION_ERROR
	SIMCONNECT_EXCEPTION_SIZE_MISMATCH                   = C.SIMCONNECT_EXCEPTION_SIZE_MISMATCH
	SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID                 = C.SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID
	SIMCONNECT_EXCEPTION_UNOPENED                        = C.SIMCONNECT_EXCEPTION_UNOPENED
	SIMCONNECT_EXCEPTION_VERSION_MISMATCH                = C.SIMCONNECT_EXCEPTION_VERSION_MISMATCH
	SIMCONNECT_EXCEPTION_TOO_MANY_GROUPS                 = C.SIMCONNECT_EXCEPTION_TOO_MANY_GROUPS
	SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED               = C.SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED
	SIMCONNECT_EXCEPTION_TOO_MANY_EVENT_NAMES            = C.SIMCONNECT_EXCEPTION_TOO_MANY_EVENT_NAMES
	SIMCONNECT_EXCEPTION_EVENT_ID_DUPLICATE              = C.SIMCONNECT_EXCEPTION_EVENT_ID_DUPLICATE
	SIMCONNECT_EXCEPTION_TOO_MANY_MAPS                   = C.SIMCONNECT_EXCEPTION_TOO_MANY_MAPS
	SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS                = C.SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS
	SIMCONNECT_EXCEPTION_TOO_MANY_REQUESTS               = C.SIMCONNECT_EXCEPTION_TOO_MANY_REQUESTS
	SIMCONNECT_EXCEPTION_WEATHER_INVALID_PORT            = C.SIMCONNECT_EXCEPTION_WEATHER_INVALID_PORT
	SIMCONNECT_EXCEPTION_WEATHER_INVALID_METAR           = C.SIMCONNECT_EXCEPTION_WEATHER_INVALID_METAR
	SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_GET_OBSERVATION  = C.SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_GET_OBSERVATION
	SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_CREATE_STATION   = C.SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_CREATE_STATION
	SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_REMOVE_STATION   = C.SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_REMOVE_STATION
	SIMCONNECT_EXCEPTION_INVALID_DATA_TYPE               = C.SIMCONNECT_EXCEPTION_INVALID_DATA_TYPE
	SIMCONNECT_EXCEPTION_INVALID_DATA_SIZE               = C.SIMCONNECT_EXCEPTION_INVALID_DATA_SIZE
	SIMCONNECT_EXCEPTION_DATA_ERROR                      = C.SIMCONNECT_EXCEPTION_DATA_ERROR
	SIMCONNECT_EXCEPTION_INVALID_ARRAY                   = C.SIMCONNECT_EXCEPTION_INVALID_ARRAY
	SIMCONNECT_EXCEPTION_CREATE_OBJECT_FAILED            = C.SIMCONNECT_EXCEPTION_CREATE_OBJECT_FAILED
	SIMCONNECT_EXCEPTION_LOAD_FLIGHTPLAN_FAILED          = C.SIMCONNECT_EXCEPTION_LOAD_FLIGHTPLAN_FAILED
	SIMCONNECT_EXCEPTION_OPERATION_INVALID_FOR_OBJECT_TYPE = C.SIMCONNECT_EXCEPTION_OPERATION_INVALID_FOR_OBJECT_TYPE
	SIMCONNECT_EXCEPTION_ILLEGAL_OPERATION               = C.SIMCONNECT_EXCEPTION_ILLEGAL_OPERATION
	SIMCONNECT_EXCEPTION_ALREADY_SUBSCRIBED              = C.SIMCONNECT_EXCEPTION_ALREADY_SUBSCRIBED
	SIMCONNECT_EXCEPTION_INVALID_ENUM                    = C.SIMCONNECT_EXCEPTION_INVALID_ENUM
	SIMCONNECT_EXCEPTION_DEFINITION_ERROR                = C.SIMCONNECT_EXCEPTION_DEFINITION_ERROR
	SIMCONNECT_EXCEPTION_DUPLICATE_ID                    = C.SIMCONNECT_EXCEPTION_DUPLICATE_ID
	SIMCONNECT_EXCEPTION_DATUM_ID                        = C.SIMCONNECT_EXCEPTION_DATUM_ID
	SIMCONNECT_EXCEPTION_OUT_OF_BOUNDS                   = C.SIMCONNECT_EXCEPTION_OUT_OF_BOUNDS
	SIMCONNECT_EXCEPTION_ALREADY_CREATED                 = C.SIMCONNECT_EXCEPTION_ALREADY_CREATED
	SIMCONNECT_EXCEPTION_OBJECT_OUTSIDE_REALITY_BUBBLE   = C.SIMCONNECT_EXCEPTION_OBJECT_OUTSIDE_REALITY_BUBBLE
	SIMCONNECT_EXCEPTION_OBJECT_CONTAINER                = C.SIMCONNECT_EXCEPTION_OBJECT_CONTAINER
	SIMCONNECT_EXCEPTION_OBJECT_AI                       = C.SIMCONNECT_EXCEPTION_OBJECT_AI
	SIMCONNECT_EXCEPTION_OBJECT_ATC                      = C.SIMCONNECT_EXCEPTION_OBJECT_ATC
	SIMCONNECT_EXCEPTION_OBJECT_SCHEDULE                 = C.SIMCONNECT_EXCEPTION_OBJECT_SCHEDULE
	SIMCONNECT_EXCEPTION_JETWAY_DATA                     = C.SIMCONNECT_EXCEPTION_JETWAY_DATA
	SIMCONNECT_EXCEPTION_ACTION_NOT_FOUND                = C.SIMCONNECT_EXCEPTION_ACTION_NOT_FOUND
	SIMCONNECT_EXCEPTION_NOT_AN_ACTION                   = C.SIMCONNECT_EXCEPTION_NOT_AN_ACTION
	SIMCONNECT_EXCEPTION_INCORRECT_ACTION_PARAMS         = C.SIMCONNECT_EXCEPTION_INCORRECT_ACTION_PARAMS
	SIMCONNECT_EXCEPTION_GET_INPUT_EVENT_FAILED          = C.SIMCONNECT_EXCEPTION_GET_INPUT_EVENT_FAILED
	SIMCONNECT_EXCEPTION_SET_INPUT_EVENT_FAILED          = C.SIMCONNECT_EXCEPTION_SET_INPUT_EVENT_FAILED
)
