//go:build ignore
// +build ignore

package sim

//go:generate go tool cgo -godefs defs.go

/*
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include "SimConnect.h"
*/
import "C"

type SIMCONNECT_RECV C.struct_SIMCONNECT_RECV
type SIMCONNECT_RECV_FACILITY_DATA C.struct_SIMCONNECT_RECV_FACILITY_DATA
type SIMCONNECT_RECV_FACILITY_DATA_END C.struct_SIMCONNECT_RECV_FACILITY_DATA_END
type SIMCONNECT_RECV_WEATHER_OBSERVATION C.struct_SIMCONNECT_RECV_WEATHER_OBSERVATION
type SIMCONNECT_RECV_CLOUD_STATE C.struct_SIMCONNECT_RECV_CLOUD_STATE
type SIMCONNECT_RECV_EXCEPTION C.struct_SIMCONNECT_RECV_EXCEPTION
type SIMCONNECT_DATA_INITPOSITION C.struct_SIMCONNECT_DATA_INITPOSITION
type SIMCONNECT_RECV_ASSIGNED_OBJECT_ID C.struct_SIMCONNECT_RECV_ASSIGNED_OBJECT_ID
type SIMCONNECT_RECV_SIMOBJECT_DATA C.struct_SIMCONNECT_RECV_SIMOBJECT_DATA

const (
	SIMCONNECT_RECV_ID_EXCEPTION              = C.SIMCONNECT_RECV_ID_EXCEPTION
	SIMCONNECT_RECV_ID_CLOUD_STATE            = C.SIMCONNECT_RECV_ID_CLOUD_STATE
	SIMCONNECT_RECV_ID_FACILITY_DATA          = C.SIMCONNECT_RECV_ID_FACILITY_DATA
	SIMCONNECT_RECV_ID_FACILITY_DATA_END      = C.SIMCONNECT_RECV_ID_FACILITY_DATA_END
	SIMCONNECT_RECV_ID_WEATHER_OBSERVATION    = C.SIMCONNECT_RECV_ID_WEATHER_OBSERVATION
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE  = C.SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE
	SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID     = C.SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA         = C.SIMCONNECT_RECV_ID_SIMOBJECT_DATA

	SIMCONNECT_FACILITY_DATA_FREQUENCY = C.SIMCONNECT_FACILITY_DATA_FREQUENCY

	SIMCONNECT_DATATYPE_INT32       = C.SIMCONNECT_DATATYPE_INT32
	SIMCONNECT_SIMOBJECT_TYPE_USER  = C.SIMCONNECT_SIMOBJECT_TYPE_USER
)
